AWSTemplateFormatVersion: 2010-09-09
Description: |
  Creating Custom VPC and Custom Public Subnet
Resources:
  MyCustomVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: 'true'
      EnableDnsSupport: 'true'
      Tags:
        - Key: Name
          Value: MyCustomVPC

  MyCustomPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/24
      VpcId: !Ref MyCustomVPC
      MapPublicIpOnLaunch: 'true'
      Tags:
        - Key: Name
          Value: MyCustomPublicSubnet
  
  MyCustomIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: MyCustomIGW
  
  AttachIGWtoVPC:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref MyCustomIGW
      VpcId: !Ref MyCustomVPC

  MyCustomRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyCustomVPC
      Tags:
        - Key: Name
          Value: MyCustomRouteTable
  
  DefineRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref MyCustomRouteTable
      GatewayId: !Ref MyCustomIGW
  
  PublicSubnetAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref MyCustomRouteTable
      SubnetId: !Ref MyCustomPublicSubnet